Add Cilium logo
walkxcode/dashboard-icons pull request #343
Opened 2023-04-09 07:59 UTC by eaglesemanation

Wanted to use it for Hubble UI

2023-04-14 17:16 UTC, walkxcode requested changes
Hello, Dashboard Icons is migrating to a new standard! Please update your pull request to match this. Read the Contributing Guide [here](https://github.com/walkxcode/dashboard-icons/blob/new-standards/CONTRIBUTING.md).

2023-04-15 05:37 UTC, eaglesemanation commented
I hope you're using squash merging, because figuring out how to use emojis in vim for commits is not something I want to spend my time on.

2023-04-15 12:55 UTC, walkxcode requested changes
Please pull the latest changes into your branch (funding.yml) and then I can merge.

2023-04-15 19:06 UTC, walkxcode approved these changes

2023-04-15 19:06 UTC, merged