🍱 adds emqx logo with new size of 512*512
walkxcode/dashboard-icons pull request #403
Opened 2023-05-04 14:03 UTC by pmfernandes

Added the png icon with 512x of height

2023-05-04 17:21 UTC, marcosandremartins approved these changes

2023-05-06 13:25 UTC, walkxcode requested changes
Please add an SVG (https://raw.githubusercontent.com/docker-library/docs/68aa4264fa058f323993fdaceacd63a8acbbeb48/emqx/logo.svg?sanitize=true) and make a new PNG from that.

2023-05-06 13:28 UTC, pmfernandes commented
> Please add an SVG (https://raw.githubusercontent.com/docker-library/docs/68aa4264fa058f323993fdaceacd63a8acbbeb48/emqx/logo.svg?sanitize=true) and make a new PNG from that.

@walkxcode: The SVG is already available in the main branch: https://github.com/walkxcode/dashboard-icons/blob/main/svg/emqx.svg

2023-05-06 13:36 UTC, walkxcode commented
Ah! Okay 😅

2023-05-06 13:36 UTC, merged